### PR TITLE
login System removed

### PR DESCRIPTION
**Pull request by rollychop**

### CODE REVIEW

**Comment by rollychop** [comment]
please consider pr

**Comment by SubhamTyagi** [comment]
@rollychop 

Could you make one PR for one commits, that will be easy to resolve conflict.

**Comment by rollychop** [comment]
Previous commit has login system and this commit such system has removed if try to pr on that you won't accept please accept yours app/build.gradle and only add java version to 1.8 and accept mine and you modify further if you want

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/loco-answers/pull/455#issuecomment-642590554


Make merge request to those commit(individual MR).  i will handle all other stuff

**Pull request closed without merging**
